name: Build and push container images for Git tags

on:
  push:
    tags:
    - "[0-9]*"
  repository_dispatch:
    types:
    - build-latest-tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Get Git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set build tag
      id: build-tag
      run: echo "::set-output name=tag::build-$(date +%Y%m%d-%H%M)"

    - name: Set version tag
      id: version-tag
      run: echo "::set-output name=tag::$(git describe --tags --match '[0-9]*' --abbrev=0)"

    - name: Checkout tag
      run: git checkout ${{ steps.version-tag.outputs.tag }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into OSG Hub
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_TOKEN }}

    - name: Build and Push k8s-hub
      uses: docker/build-push-action@v2
      with:
        context: containers/k8s-hub
        push: true
        tags: |
          hub.opensciencegrid.org/osg-jupyter/k8s-hub:${{ steps.build-tag.outputs.tag }}
          hub.opensciencegrid.org/osg-jupyter/k8s-hub:${{ steps.version-tag.outputs.tag }}
